local keymap = vim.keymap.set
local opts = { noremap = true }

-- nnoremap "n"
-- vnoremap "v"
-- xnoremap "x"
-- inoremap "i"
-- vim.keymap.set(type, keys, command, options)

-- Vim
keymap("n", "<Leader>f", ":Ex<CR>")
keymap("n", "H", "^")
keymap("n", "L", "$")
keymap("v", "L", "$h")
keymap("v", "<", "<gv")
keymap("v", ">", ">gv")
keymap("n", "<C-J>", "<C-W><C-J>")
keymap("n", "<C-K>", "<C-W><C-K>")
keymap("n", "<C-L>", "<C-W><C-L>")
keymap("n", "<C-H>", "<C-W><C-H>")
keymap("x", "<leader>p", "\"+p")
keymap("n", "<leader>y", "\"+y")
keymap("v", "<leader>y", "\"+y")
keymap("n", "<leader>k", ":bd<CR>")
keymap("n", "<leader>K", ":bd!<CR>")
keymap("n", "<leader>s", ":w<CR>")
keymap("i", "jk", "<esc>")

-- LSP
keymap("n", "gd", function()
  vim.lsp.buf.definition()
end)
keymap("n", "gD", function()
  vim.lsp.buf.declaration()
end)
keymap("n", "gi", function()
  vim.lsp.buf.implementation()
end)
keymap("n", "gw", function()
  vim.lsp.buf.document_symbol()
end)
keymap("n", "gw", function()
  vim.lsp.buf.workspace_symbol()
end)
keymap("n", "gr", function()
  vim.lsp.buf.references()
end)
keymap("n", "gt", function()
  vim.lsp.buf.type_definition()
end)
keymap("n", "K", function()
  vim.lsp.buf.hover()
end)
keymap("n", "<c-k>", function()
  vim.lsp.buf.signature_help()
end)
keymap("n", "<leader>af", function()
  vim.lsp.buf.code_action()
end)
keymap("n", "<leader>rn", function()
  vim.lsp.buf.rename()
end)
keymap("n", "<leader>e", vim.diagnostic.open_float)

-- Telescope
keymap("n", "<C-p>", function()
  require("telescope.builtin").git_files()
end)
keymap("n", "<leader>ps", function()
  require("telescope.builtin").live_grep()
end)
keymap("n", "<Leader>pf", function()
  require("telescope.builtin").find_files({ hidden = true, ignore = true, find_command = rg })
end)
keymap("n", "<leader>pw", function()
  require("telescope.builtin").grep_string({ search = vim.fn.expand("<cword>") })
end)
keymap("n", "<leader>pb", function()
  require("telescope.builtin").buffers()
end)
keymap("n", "<leader>vh", function()
  require("telescope.builtin").help_tags()
end)
keymap("n", "<leader>ph", ":Telescope harpoon marks<cr>")

-- Harpoon
keymap("n", "<leader>h", function()
  require("harpoon.mark").add_file()
end)
keymap("n", "<leader>ht", function()
  require("harpoon.ui").toggle_quick_menu()
end)
keymap("n", "<leader>hn", function()
  require("harpoon.ui").nav_next()
end)
keymap("n", "<leader>hp", function()
  require("harpoon.ui").nav_prev()
end)
